name: AppverAutoUpdate

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

# 明确赋予云端机器人写入文件的权限
permissions:
  contents: write

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      # 升级到 v4 消除警告
      - name: 检出代码
        uses: actions/checkout@v4

      # 升级到 v5 消除警告
      - name: 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install requests

      - name: 运行爬虫脚本
        run: python update_source.py

      - name: 提交并推送到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update App version" && git push)
